const socketTypes = {
    CREATE_ROOM: 'CREATE_ROOM',
    ROOM_CREATED: 'ROOM_CREATED',
    JOIN_ROOM: 'JOIN_ROOM',
    JOIN_ROOM_SUCCESS: 'JOIN_ROOM_SUCCESS',
    JOIN_ROOM_ERROR: 'JOIN_ROOM_ERROR',
    ADD_PLAYER: 'ADD_PLAYER',
    UPDATE_PLAYER: 'UPDATE_PLAYER',
    REMOVE_PLAYER: 'REMOVE_PLAYER',
    PLAYER_ADDED: 'PLAYER_ADDED',
    PLAYER_REMOVED:'PLAYER_REMOVED',
    UPDATE_PLAYER_LIST: 'UPDATE_PLAYER_LIST',
    UPDATE_SCENE: 'UPDATE_SCENE',
    SCENE_UPDATED: 'SCENE_UPDATED',
    INIT: 'INIT',
    ERROR: 'ERROR',
}

export default socketTypes;